
title: Yet Another Cool Blog Title
#email: p.faion@web.de
description: >
  This will be my awesome blog once I have it set up.


sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-coffeescript


# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
